### ISSUE TITLE
Support Application-only authentication

### ISSUE THREAD

**Issue by kavdev** [twitterdev/twitter-python-ads-sdk#102]
https://dev.twitter.com/oauth/application-only

Looking into the source a bit, I'll be having a bit of fun getting this to work :). OAuth2 support out of the box would be nice

**Comment by kavdev** [comment]
Decided to just use the app's access token, so this is isn't urgent and might not be worth implementing -- I'm not sure what benefits app-only auth brings besides a different rate limit.

**Comment by jbabichjapan** [comment]
Actually the only area in Ads API realm where app-only auth is used is for "mobile attribution conversion tracking" solutions, for other Ads API the auth must be 3-legged and based off of the same sort of access token structure you may find in the .twurlrc file.

You can think of that it is sort of used for security as well because some ad accounts contain private / sensitive information.

**Comment by jbabichjapan** [comment]
Thanks for the contributions you are making though and feel free to keep posting issues / Qs, much appreciated!

**Comment by kavdev** [comment]
@jbabichjapan: Thanks for the info! That would be great to have in the official Ads API docs.
