### ISSUE TITLE
Does this library handles login?

### ISSUE THREAD

**Issue by Cosbgn** [twitterdev/twitter-python-ads-sdk#124]
I need to fetch ads data for my users. I looked around and it seems that this library does not provide any login, so I'm using oauthlib requests and I'm doing a standard oauth1 authentication.

My doubts are:
when I build the client with:
```
client = Client(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
```
The consumer keys are mine while the access token and access token secret are from the users right? Should I ask some extra permissions (i.e. scope) to access ads data? 

Thanks

**Comment by jbabichjapan** [comment]
Generally we leave it to implementation to decide how to handle OAuth because how you store the keys and go through 3-legged auth will be different from company to company.

The permissions will be handled by our side based upon your app ID and app settings.

The main advice I have is that twurl the command line tool wrapper for curl has a built in OAuth key storage that is file based. I would recommend to keep the user tokens in a secure location / even encrypted (e.g. inside a DB), and how you go through auth can be done in many different ways but essentially this part is not different from the Twitter public API and authing a handle to use an application.
