### ISSUE TITLE
Resource mixin missing account_id  for some resources

### ISSUE THREAD

**Issue by raethlo** [twitterdev/twitter-python-ads-sdk#164]
Hey all,

Currently, calling `Resource.to_params()` omits `account_id` field because the classes deriving from Resource don't have it listed as a [`resource_property`](https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/twitter_ads/resource.py#L22).

I would imagine calling [`.to_params()`](https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/twitter_ads/resource.py#L64) results in a output similar to a one used [when calling the API](https://developer.twitter.com/en/docs/ads/campaign-management/api-reference/campaigns) on that resource. That means having the `account_id` set (at least) on Campaign and Line Item resources.

Can we consider adding at least a readonly `account_id` resource_property to the classes that should be able to access it or alternatively augment the output of `.to_params()` to include `account_id` field wherever applicable?

**Comment by smaeda-ks** [comment]
Hi @raethlo, Thanks for your feedback (and sorry for replying such an old topic today...).

Though, if you're still there looking for this improvement, could you please provide us a bit more context as to why you want that data through `.to_params()` method? Because when you create a client instance you know what's the account_id you're trying to access, right? What's the use case for this? Thanks!
