### ISSUE TITLE
Cannot save LineItem without setting advertiser_user_id to None

### ISSUE THREAD

**Issue by josephtyler** [twitterdev/twitter-python-ads-sdk#165]
Trying to save a LineItem results in:

```
{'message': 'setting advertiser_user_id is not allowed', 'code': 'INVALID_PARAMETER', 'parameter': 'advertiser_user_id'
```

I'm not explicitly setting this value, but it seems to be getting set. In any case, the following hack allows me to save:

```
line_item.advertiser_user_id = None
line_item.save()
```

**Comment by smaeda-ks** [comment]
This is because our [GET accounts/:account_id/line_items](https://developer.twitter.com/en/docs/ads/campaign-management/api-reference/line-items#get-accounts-account-id-line-items) endpoint returns this field by default and we carry these values into the request object. So even if you're not setting this value, there's a value already and you need to do this or remove this key from the object since specifying `advertiser_user_id` parameter is allowed for whitelisted advertisers only.
