### ISSUE TITLE
Getting Forbidden Error

### ISSUE THREAD

**Issue by karthikr44** [twitterdev/twitter-python-ads-sdk#43]
Hi,

After i create an app in Twitter, given the consumer key, token and all other details. 

When i execute the program, getting the following error, 

Traceback (most recent call last):
  File "twitad_pull.py", line 15, in <module>
    account = client.accounts(ACCOUNT_ID)
  File "/usr/local/lib/python2.7/dist-packages/twitter_ads/client.py", line 89, in accounts
    return Account.load(self, id) if id else Account.all(self)
  File "/usr/local/lib/python2.7/dist-packages/twitter_ads/account.py", line 46, in load
    response = Request(client, 'get', resource, params=kwargs).perform()
  File "/usr/local/lib/python2.7/dist-packages/twitter_ads/http.py", line 59, in perform
    raise Error.from_response(response)
<b>twitter_ads.error.Forbidden</b>

Please share us your thoughts. 

thanks,
r karthik.

**Comment by andypiper** [comment]
Is your account whitelisted for the use of the Ads API? see https://dev.twitter.com/ads/overview/getting-started

**Comment by brandonblack** [comment]
@karthikr44 403 responses occur when you don't have permission to access a given resource. Since you're just trying to list available accounts here, it's likely your application isn't yet white-listed to access the Twitter Ads API.

The API is still part of a closed partner program at the moment but you can [apply for access here](https://dev.twitter.com/ads/overview) and our BD team will process your application.

If you have any additional questions about the partner program, you may get answers quicker over in the [Twitter developer forums](https://twittercommunity.com/c/advertiser-api) as @andypiper suggested.

If you have additional questions about the SDK itself please feel free to open another question ticket here or you can also ask about it in the forums.
