### ISSUE TITLE
Create an "Open Call" for Community Maintainers

### ISSUE THREAD

**Issue by brandonblack** [twitterdev/twitter-python-ads-sdk#98]
I'd like to propose that we open this project up to additional maintainers from the community. ✨ 

Once pull request approvals [are correctly enabled](https://github.com/twitterdev/twitter-python-ads-sdk/pull/97), I'd love to see us give write access to our more active members of the community and establish a process for requesting a release to pypy from the Twitter team.

My recommendations for potential maintainers (if they're willing):
- @frewsxcv https://github.com/twitterdev/twitter-python-ads-sdk/commits?author=frewsxcv

---
CC: @jaakko-sf @jbabichjapan 
Depends On: twitterdev/twitter-python-ads-sdk#97

**Comment by frewsxcv** [comment]
Thanks for the offer! Had this been a few months ago, I would have been more than willing to help maintain, but due to project changes, I don't think I'll be interacting with the Twitter Ads API much in the future, so I'm not sure it makes sense to delegate anything to me. I definitely am in favor of the concept of giving the community access though!
